package rules

import com.borjaeg.drools.Treatment;


query getUsersForCard
    $listOfUserCards : Treatment(getProduct() == 'sulfur')
end


rule "sulfur-appletree-spider" 
//@Defeasible
dialect "java"

when
    $treatment : Treatment (getProduct() == 'sulfur', getCrop() == 'appletree', getPlague() == 'spider', isForbidden() == false)
then
    $treatment.setMessage($treatment.getMessage() + "OK"); 
    insert($treatment);
end

rule "f-sulfur-appletree-spider"
//@Defeater
//@Defeats("sulfur-appletree-spider")
dialect "java"
salience 1
no-loop

when
    $treatment : Treatment (getProduct() == 'sulfur', getCrop() == 'appletree', getPlague() == 'spider')
then
	$treatment.setForbidden(true);
	$treatment.setMessage($treatment.getMessage() + "FORBIDDEN");
	update($treatment);
end